# filepath: /home/chris/Documents/St. Tim's Church Music Project 2025/vite-churchmusicsite/supabase/config.toml

# Configures the Supabase project settings.
# See https://supabase.com/docs/reference/cli/config

project_id = "st-tims-church-music-project-2025" # Optional: A human-readable identifier

[api]
port = 54321
schemas = ["public", "storage", "graphql"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15 # Or match your project's version

[studio]
port = 54323

# Settings pulled from remote project 'xaytwwttwhnidxflmypj'
[auth]
enabled = true
site_url = "https://sttimssheffieldmusic.netlify.app" # From remote
# additional_redirect_urls = [] # From remote (empty or omit)
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 3 # From remote
[auth.mfa.totp]
enroll_enabled = true # From remote
verify_enabled = true # From remote
[auth.mfa.phone]
enroll_enabled = false # Assuming default/remote
verify_enabled = false # Assuming default/remote

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true # From remote
secure_password_change = true # From remote
max_frequency = "1m0s" # From remote
otp_length = 6
otp_expiry = 1000 # From remote

[auth.sms]
enable_signup = false
# Add other sections like [storage], [functions] if needed,
# but keep them minimal unless you have specific local overrides.